global:
  scrape_interval:      15s
  evaluation_interval:  15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: "statsd-exporter"
    static_configs:
      - targets: ['localhost:9102']

  - job_name: cloudwatch_logs
    static_configs:
      - targets: ['localhost:9106']

  - job_name: mongo
    static_configs:
      - targets: ['mongo.ndc-preprod.internal:9216']